# Generated by compat/gsplat_overload/generate.py. Do not edit.
from importlib import import_module as _import_module

_impl = _import_module("ptxsplat.cuda._torch_impl")
for _name in dir(_impl):
    if not _name.startswith("__"):
        globals()[_name] = getattr(_impl, _name)

__all__ = getattr(_impl, "__all__", getattr(_impl, "all", []))


def __getattr__(name):
    return getattr(_impl, name)


def __dir__():
    return sorted(set(globals()) | set(dir(_impl)))
