"""Generate thin gsplat modules that forward to the ptxsplat package tree."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "ptxsplat"
DESTINATION = Path(__file__).resolve().parent / "gsplat"

TEMPLATE = '''# Generated by compat/gsplat_overload/generate.py. Do not edit.
from importlib import import_module as _import_module

_impl = _import_module("{module}")
for _name in dir(_impl):
    if not _name.startswith("__"):
        globals()[_name] = getattr(_impl, _name)

__all__ = getattr(_impl, "__all__", getattr(_impl, "all", []))


def __getattr__(name):
    return getattr(_impl, name)


def __dir__():
    return sorted(set(globals()) | set(dir(_impl)))
'''


def generated_modules() -> dict[Path, str]:
    modules = {}
    for source in sorted(SOURCE.rglob("*.py")):
        relative = source.relative_to(SOURCE)
        parts = list(relative.parts)
        if parts[-1] == "__init__.py":
            parts = parts[:-1]
        else:
            parts[-1] = Path(parts[-1]).stem
        module = ".".join(["ptxsplat", *parts])
        modules[relative] = TEMPLATE.format(module=module)
    return modules


def check() -> None:
    expected = generated_modules()
    actual = {
        path.relative_to(DESTINATION): path.read_text(encoding="ascii")
        for path in DESTINATION.rglob("*.py")
    }
    if actual != expected:
        missing = sorted(set(expected) - set(actual))
        extra = sorted(set(actual) - set(expected))
        changed = sorted(path for path in expected.keys() & actual.keys() if expected[path] != actual[path])
        raise SystemExit(
            f"generated overload is stale: missing={missing}, extra={extra}, changed={changed}"
        )


def generate() -> None:
    if DESTINATION.exists():
        shutil.rmtree(DESTINATION)

    for relative, contents in generated_modules().items():
        destination = DESTINATION / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(contents, encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    check() if args.check else generate()


if __name__ == "__main__":
    main()
