"""Generate thin gsplat modules that forward to the ptxsplat package tree."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "ptxsplat"
DESTINATION = Path(__file__).resolve().parent / "gsplat"

TEMPLATE = '''# Generated by compat/gsplat_overload/generate.py. Do not edit.
from importlib import import_module as _import_module

_impl = _import_module("{module}")
for _name in dir(_impl):
    if not _name.startswith("__"):
        globals()[_name] = getattr(_impl, _name)

__all__ = getattr(_impl, "__all__", getattr(_impl, "all", []))


def __getattr__(name):
    return getattr(_impl, name)


def __dir__():
    return sorted(set(globals()) | set(dir(_impl)))
'''


def main() -> None:
    if DESTINATION.exists():
        shutil.rmtree(DESTINATION)

    for source in sorted(SOURCE.rglob("*.py")):
        relative = source.relative_to(SOURCE)
        destination = DESTINATION / relative
        destination.parent.mkdir(parents=True, exist_ok=True)

        parts = list(relative.parts)
        if parts[-1] == "__init__.py":
            parts = parts[:-1]
        else:
            parts[-1] = Path(parts[-1]).stem
        module = ".".join(["ptxsplat", *parts])
        destination.write_text(TEMPLATE.format(module=module), encoding="ascii")


if __name__ == "__main__":
    main()
